
server:
  port: 8086
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tJWUumWWh4evahQybgk
      secret-key: xjHapQ7IvuFYrbyEn0J50DMgwAOj1P
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-zhy
